'use client';
import {useState,useEffect,useRef} from 'react';
import {Mountain,MapPin,CalendarDays,Wallet,ListChecks,Backpack,Settings,Plus,Pencil,Trash2,ArrowUpRight,TrainFront,Users,Check,Lock,Cloud,RefreshCw,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {initialTrip,dateAt,Trip,Event,Task,Expense,Tip} from './trip-data';
const tabs=[['plan','每日行程',CalendarDays],['money','旅行账本',Wallet],['todo','待办清单',ListChecks],['prepare','行前准备',Backpack],['settings','旅行设置',Settings]] as const;
const money=(n:number)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(n);
const uid=()=>crypto.randomUUID();
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <label className="field">{label}<Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[...new Set([value,...options])].filter(Boolean).map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>}
function Field({label,value,onChange,type='text',required=false,min,max,step}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string;required?:boolean;min?:number;max?:number;step?:string}){return <label className="field">{label}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} min={min} max={max} step={step}/></label>}
type Modal={kind:'event';data:Event}|{kind:'task';data:Task}|{kind:'expense';data:Expense}|{kind:'tip';data:Tip}|{kind:'login'};
export default function Home(){
const [trip,setTrip]=useState<Trip>(initialTrip),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[canEdit,setCanEdit]=useState(false),[editing,setEditing]=useState(false),[tab,setTab]=useState('plan'),[day,setDay]=useState(0),[modal,setModal]=useState<Modal|null>(null),[remove,setRemove]=useState<{kind:'events'|'tasks'|'expenses'|'tips';id:string}|null>(null),[key,setKey]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[updated,setUpdated]=useState<string|null>(null),[settings,setSettings]=useState<Trip|null>(null),[filter,setFilter]=useState('全部'),[taskFilter,setTaskFilter]=useState('全部');
const busyRef=useRef(false);const latest=useRef({trip,revision,loaded});latest.current={trip,revision,loaded};const totalPeople=trip.families.reduce((s,f)=>s+f.members.length,0),total=trip.expenses.reduce((s,e)=>s+Math.round(e.amount*100),0)/100,done=trip.tasks.filter(t=>t.done).length;
async function load(silent=false){try{const r=await fetch('/api/trip',{cache:'no-store'});const b=await r.json() as {error?:string;trip:Trip;revision:number;updated:string|null;canEdit:boolean};if(!r.ok)throw Error(b.error||'请求失败，请重试');setTrip(b.trip);setRevision(b.revision);setUpdated(b.updated);setCanEdit(b.canEdit);setLoaded(true);if(!silent)setError('');}catch(e){if(!silent)setError((e as Error).message)}}
useEffect(()=>{void load();},[]);
useEffect(()=>{if(editing||modal)return;const timer=setInterval(()=>{if(!document.hidden&&!busyRef.current)void load(true)},15000);return()=>clearInterval(timer)},[editing,modal]);
useEffect(()=>{if(day>=trip.days)setDay(trip.days-1)},[trip.days,day]);
useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!context)return;const ctrl=new AbortController();try{context.registerTool({name:'read_trip_plan',description:'读取当前显示的家庭行程和待办，不修改数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return latest.current}},{signal:ctrl.signal})}catch{}return()=>ctrl.abort()},[]);
async function save(next:Trip){if(!editing||busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');try{const r=await fetch('/api/trip',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip:next,revision})});const b=await r.json() as {error?:string;trip:Trip;revision:number;updated:string|null;canEdit:boolean};if(!r.ok)throw Error(b.error||'请求失败，请重试');setTrip(next);setRevision(b.revision);setUpdated(b.updated);setNotice('已保存，家人的页面会自动更新');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false);busyRef.current=false}}
async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/editor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});const b=await r.json() as {error?:string;trip:Trip;revision:number;updated:string|null;canEdit:boolean};if(!r.ok)throw Error(b.error||'请求失败，请重试');setCanEdit(true);setEditing(true);setModal(null);setKey('');setNotice('已进入编辑模式')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function toggleEdit(){setError('');if(editing){setEditing(false);setSettings(null)}else if(canEdit)setEditing(true);else setModal({kind:'login'})}
function edit(kind:Modal['kind'],data?:Event|Task|Expense|Tip){setError('');if(kind==='event')setModal({kind,data:(data as Event)||{id:uid(),day,time:'',title:'',location:'',people:'全员',status:'待安排',notes:''}});if(kind==='task')setModal({kind,data:(data as Task)||{id:uid(),title:'',category:'行前',owner:'我',done:false}});if(kind==='expense')setModal({kind,data:(data as Expense)||{id:uid(),title:'',category:'餐饮',amount:0,date:dateAt(trip.start,day),payer:'我',group:'共同',notes:''}});if(kind==='tip')setModal({kind,data:(data as Tip)||{id:uid(),title:'',notes:''}})}
function updateModal(prop:string,value:unknown){setModal(m=>m&&m.kind!=='login'?{...m,data:{...m.data,[prop]:value}} as Modal:m)}
async function submitModal(e:React.FormEvent){e.preventDefault();if(!modal||modal.kind==='login')return;const collection=({event:'events',task:'tasks',expense:'expenses',tip:'tips'} as const)[modal.kind];const data=modal.data;const list=(trip[collection] as {id:string}[]).filter(x=>x.id!==data.id);const next={...trip,[collection]:[...list,data]};if(collection==='events')next.events.sort((a,b)=>a.day-b.day);if(await save(next))setModal(null)}
const dayEvents=trip.events.filter(e=>e.day===day);const dayTitles=['汇合，向长白山出发','北坡一日，去看天池','旅拍、温泉与小镇夜色','森林漂流，然后回长春','长春慢生活','闲逛、美食与返程'];
const action=(kind:'event'|'task'|'expense'|'tip',data:Event|Task|Expense|Tip)=><span className="actions"><button aria-label={'编辑'+data.title} onClick={()=>edit(kind,data)}><Pencil size={16}/></button><button aria-label={'删除'+data.title} onClick={()=>{setError('');setRemove({kind:({event:'events',task:'tasks',expense:'expenses',tip:'tips'} as const)[kind],id:data.id})}}><Trash2 size={16}/></button></span>;
return <main className="shell"><header><div className="brand"><span className="brand-icon"><Mountain size={24}/></span><div><b>{trip.title}</b><small>我们的家庭旅行手册</small></div></div><div className="top-actions"><span className="sync"><Cloud size={15}/>{loaded?'共享云端':'连接中'}</span><button className={editing?'btn primary':'btn'} disabled={!loaded||busy} onClick={toggleEdit}>{editing?<Check size={16}/>:<Pencil size={16}/>} {editing?'完成编辑':'编辑攻略'}</button></div></header>
<section className="hero"><div><div className="eyebrow">CHANGBAISHAN · FAMILY TRIP</div><h1>把秋天，留在长白山。</h1><p>北京 <span>→</span> 长春 <span>→</span> 二道白河</p><div className="hero-chips"><span><CalendarDays size={15}/>{trip.start.replaceAll('-','.')} — {dateAt(trip.start,trip.days-1).slice(5).replace('-','.')}</span><span><Users size={15}/>{totalPeople} 位家人 · {trip.families.length} 个家庭</span></div></div><div className="hero-note">天池 · 秋日雪景<small>行程依天气与景区开放情况调整</small></div></section>
<div className="overview"><div><strong>{trip.days.toString().padStart(2,'0')}</strong><span>天的旅行计划</span></div><div><strong>{trip.events.length.toString().padStart(2,'0')}</strong><span>个行程安排</span></div><div><strong>{done}<i> / {trip.tasks.length}</i></strong><span>项准备已完成</span></div><div><strong>{money(total)}</strong><span>实际支出 · 人均 {money(total/Math.max(totalPeople,1))}</span></div></div>
{editing&&<div className="edit-banner"><Pencil size={16}/><span>编辑模式 · 每次点击保存后同步给家人</span><button onClick={async()=>{await fetch('/api/editor',{method:'DELETE'});setEditing(false);setCanEdit(false);setSettings(null)}}>退出编辑权限</button></div>}
{error&&!modal&&!remove&&<div role="alert" className="error">{error}<button className="btn" onClick={()=>load()}>重新载入</button></div>}
{notice&&<div role="status" className="toast"><Check size={16}/>{notice}</div>}
<Tabs value={tab} onValueChange={v=>{setTab(v);setFilter('全部')}}><TabsList className="main-tabs">{tabs.map(([id,label,Icon])=><TabsTrigger key={id} value={id}><Icon size={18}/><span>{label}</span></TabsTrigger>)}</TabsList>
<TabsContent value="plan"><div className="trip-layout"><aside className="day-nav"><p className="eyebrow">这趟旅程</p>{Array.from({length:trip.days},(_,i)=><button key={i} className={day===i?'day-button selected':'day-button'} onClick={()=>setDay(i)}><span className="day-index">{String(i+1).padStart(2,'0')}</span><span><b>{dateAt(trip.start,i).slice(5).replace('-',' 月 ')} 日</b><small>{i<4?'长白山之旅':i<6?'长春延伸行程':'自由安排'}</small></span><ChevronRight size={16}/></button>)}<div className="aside-note"><MapPin size={18}/><b>二道白河 · 三晚</b><p>原计划 10 月 1—3 日入住同一民宿；名称与地址待补全。</p></div></aside><section className="itinerary"><div className="section-heading"><div><span className="eyebrow">DAY {String(day+1).padStart(2,'0')} / {dateAt(trip.start,day)}</span><h2>{dayTitles[day]||'留一点时间，自由探索'}</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('event')}><Plus size={16}/>添加行程</button>}</div><p className="muted">{day===2?'上午分头活动，下午一起泡温泉。':day===3?'漂流与高铁同一天，留足返程缓冲。':'点击行程查看具体安排、参与人和预订备注。'}</p><div className="timeline">{dayEvents.length?dayEvents.map(e=><article className="event" key={e.id}><div className="event-marker"><TrainFront size={19}/></div><div className="event-body"><div className="event-top"><span>{e.time||'时间待定'}</span><span className={'badge '+(e.status==='已确认'?'confirmed':'')}>{e.status}</span></div><button className="event-title" onClick={()=>edit('event',e)}>{e.title}<ArrowUpRight size={17}/></button><p><MapPin size={14}/>{e.location||'地点待补充'}<span>·</span>{e.people}</p>{editing&&action('event',e)}</div></article>):<div className="empty">这一天还没有安排。{editing?'点击“添加行程”开始规划。':'留给自由探索。'}</div>}</div></section></div></TabsContent>
<TabsContent value="money"><div className="section-heading"><div><span className="eyebrow">TRAVEL EXPENSES</span><h2>花在哪里，记在一起。</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('expense')}><Plus size={16}/>记一笔</button>}</div><div className="money-summary"><section className="panel"><small>累计实际支出</small><h2>{money(total)}</h2><p>预算 {trip.budget?money(trip.budget):'未设置'}{trip.budget>0&&' · 剩余 '+money(trip.budget-total)}</p></section><section className="panel"><small>按费用归属统计</small>{['共同',...trip.families.map(f=>f.name)].map(g=><p className="between" key={g}><span>{g}</span><b>{money(trip.expenses.filter(e=>e.group===g).reduce((s,e)=>s+Math.round(e.amount*100),0)/100)}</b></p>)}<small>人均仅作参考，不代表两家结算金额。</small></section></div><div className="filters">{['全部',...new Set(trip.expenses.map(e=>e.category))].map(c=><button key={c} className={filter===c?'chip active':'chip'} onClick={()=>setFilter(c)}>{c}</button>)}</div><section className="panel expense-list">{trip.expenses.filter(e=>filter==='全部'||e.category===filter).length?trip.expenses.filter(e=>filter==='全部'||e.category===filter).map(e=><article key={e.id} className="expense"><span className="expense-icon"><Wallet size={20}/></span><div><b>{e.title}</b><small>{e.date} · {e.category} · {e.payer}付款 · {e.group}</small>{e.notes&&<p>{e.notes}</p>}</div><strong>{money(e.amount)}</strong>{editing&&action('expense',e)}</article>):<div className="empty"><Wallet size={36}/><h3>第一笔旅费，还没记下</h3><p>这里记录实际花费；预订计划放在待办里。</p>{editing&&<button className="btn" onClick={()=>edit('expense')}>记录第一笔支出</button>}</div>}</section></TabsContent>
<TabsContent value="todo"><div className="section-heading"><div><span className="eyebrow">BEFORE WE GO</span><h2>一件件准备，安心出发。</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('task')}><Plus size={16}/>添加待办</button>}</div><section className="panel"><div className="between"><b>准备进度</b><span>{done} / {trip.tasks.length} 已完成</span></div><Progress className="my-4 h-2" value={trip.tasks.length?done/trip.tasks.length*100:0}/><div className="filters">{['全部','未完成','已完成'].map(c=><button key={c} className={taskFilter===c?'chip active':'chip'} onClick={()=>setTaskFilter(c)}>{c}</button>)}</div>{!editing&&<p className="muted">查看模式 · 进入编辑模式可勾选完成事项。</p>}{trip.tasks.filter(t=>taskFilter==='全部'||t.done===(taskFilter==='已完成')).map(t=><div className="task" key={t.id}><Checkbox aria-label={'完成：'+t.title} checked={t.done} disabled={!editing||busy} onCheckedChange={v=>save({...trip,tasks:trip.tasks.map(x=>x.id===t.id?{...x,done:v===true}:x)})}/><div><span className={t.done?'completed':''}>{t.title}</span><small>{t.category} · {t.owner||'未分配'}</small></div>{editing&&action('task',t)}</div>)}{!trip.tasks.filter(t=>taskFilter==='全部'||t.done===(taskFilter==='已完成')).length&&<div className="empty">此分类暂无待办。</div>}</section></TabsContent>
<TabsContent value="prepare"><div className="section-heading"><div><span className="eyebrow">PACK LIGHT, PLAN WELL</span><h2>把准备做好，把心情放松。</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('tip')}><Plus size={16}/>添加提醒</button>}</div><div className="weather-note"><Backpack size={25}/><div><b>天气与景区开放 · 临行核实</b><p>不将历史天气或往年烟花安排当成本次承诺。山顶与镇内天气要分别确认。</p><a href="https://www.changbaishan.gov.cn/" target="_blank" rel="noreferrer">长白山官方信息 ↗</a><a href="https://www.cbsslc.com/" target="_blank" rel="noreferrer">露水河景区 ↗</a></div></div><div className="tips-grid">{trip.tips.map((t,i)=><section className="panel" key={t.id}><span className="tip-number">0{i+1}</span><h3>{t.title}</h3><p>{t.notes}</p>{editing&&action('tip',t)}</section>)}</div><section className="panel"><h3>核对记录</h3><p>景区名称按官方资料整理为“露水河”“恩都里”。活动时间、票价和具体套餐以本次预订确认为准。</p><p><a href="https://www.changbaishan.gov.cn/zwgk/zwdt/zbsyw/202510/t20251010_268517.html" target="_blank" rel="noreferrer">恩都里往年活动资料（2025 年，不是 2026 年场次表）↗</a></p><small>资料整理：2026-09-24；提醒可在编辑模式修改。</small></section></TabsContent>
<TabsContent value="settings"><div className="section-heading"><div><span className="eyebrow">OUR TRIP</span><h2>这趟旅行，我们一起。</h2></div></div><section className="panel"><form onSubmit={async e=>{e.preventDefault();if(!settings)return;const maxDay=Math.max(-1,...trip.events.map(e=>e.day));if(settings.days<=maxDay){setError(`第 ${maxDay+1} 天仍有行程，请先移动或删除这些行程，再缩短天数。`);return}if(await save({...trip,title:settings.title,start:settings.start,days:settings.days,budget:settings.budget,families:settings.families}))setSettings(null)}}><fieldset disabled={!editing||busy}><div className="form-grid"><Field label="旅行名称" required value={(settings||trip).title} onChange={v=>setSettings({...settings||trip,title:v})}/><Field label="起始日期" required type="date" value={(settings||trip).start} onChange={v=>setSettings({...settings||trip,start:v})}/><Field label="旅行总天数（含长春）" type="number" required min={1} max={30} value={(settings||trip).days} onChange={v=>setSettings({...settings||trip,days:Number(v)})}/><Field label="总预算（元，0 表示未设置）" type="number" min={0} step="0.01" value={(settings||trip).budget} onChange={v=>setSettings({...settings||trip,budget:Number(v)})}/></div><p className="muted">修改起始日期会整体移动行程日期；记账日期保留实际发生日期。具体车票与民宿备注请同步核对。</p><h3>同行的家人</h3>{(settings||trip).families.map((f,i)=><div className="family-row" key={i}><Field label={'家庭 '+(i+1)} value={f.name} required onChange={v=>{const n=structuredClone(settings||trip);n.families[i].name=v;setSettings(n)}}/><Field label="成员（用中文逗号分隔）" value={f.members.join('，')} required onChange={v=>{const n=structuredClone(settings||trip);n.families[i].members=v.split(/[，,]/);setSettings(n)}}/>{editing&&<button type="button" className="btn" disabled={(settings||trip).families.length<=1} onClick={()=>{const n=structuredClone(settings||trip);n.families.splice(i,1);setSettings(n)}}>移除家庭</button>}</div>)}{editing&&<div className="form-actions"><button type="button" className="btn" onClick={()=>{const n=structuredClone(settings||trip);n.families.push({name:'新家庭',members:['新成员']});setSettings(n)}}>＋ 添加家庭</button><button className="btn primary" type="submit" disabled={!settings||busy}>{busy?'保存中…':'保存旅行设置'}</button></div>}</fieldset></form><p className="muted">共 {(settings||trip).families.reduce((s,f)=>s+f.members.filter(m=>m.trim()).length,0)} 位成员 · 人数自动联动概览与人均支出。</p></section><section className="panel"><h3>共享与更新</h3><p>修改保存到同一份云端攻略。家人查看时每 15 秒自动检查更新；编辑模式不会自动覆盖草稿。</p><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin);setNotice('查看链接已复制')}catch{setError('复制失败，请复制浏览器地址栏链接。')}}}>复制查看链接</button><p className="muted">编辑口令请只由你保管。切换到查看模式不会清除权限，使用“退出编辑权限”可锁定。</p></section></TabsContent></Tabs>
<footer><span>{updated?'最近保存 '+new Date(updated).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})+'（北京时间）':'行程初稿 · 待预订项目已单独标记'}</span><button disabled={busy||editing} onClick={()=>load()}><RefreshCw size={13}/>刷新</button><div>照片：<a href="https://commons.wikimedia.org/wiki/File:Tianchi_Lake_Panorama.jpg" target="_blank" rel="noreferrer">Sinopitt / Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noreferrer">CC BY-SA 3.0</a> · 展示裁剪</div></footer>
<Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy){setModal(null);setError('')}}}><DialogContent className="trip-dialog"><DialogTitle>{modal?.kind==='login'?'解锁编辑模式':modal?.kind==='event'?'行程详情':modal?.kind==='task'?'待办事项':modal?.kind==='expense'?'记录一笔支出':'行前提醒'}</DialogTitle><DialogDescription>{modal?.kind==='login'?'输入你的专属编辑口令。家人无需口令即可使用查看模式。':editing?'修改后点击保存，同步给家人。':'查看模式 · 具体预订情况以订单为准。'}</DialogDescription>{error&&<div role="alert" className="error">{error}</div>}{modal?.kind==='login'?<form onSubmit={login}><Field label="编辑口令" type="password" required value={key} onChange={setKey}/><button className="btn primary mt-4" disabled={busy}>{busy?'验证中…':'进入编辑模式'}</button></form>:modal&&<form onSubmit={submitModal}><fieldset disabled={!editing||busy}>
{modal.kind==='event'&&<><Field label="活动名称" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><div className="form-grid"><Choice label="旅行第几天" value={String(modal.data.day+1)} options={Array.from({length:trip.days},(_,i)=>String(i+1))} onChange={v=>updateModal('day',Number(v)-1)}/><Field label="时间 / 时段" value={modal.data.time} onChange={v=>updateModal('time',v)}/></div><Field label="地点 / 地址" value={modal.data.location} onChange={v=>updateModal('location',v)}/><Field label="参与人" value={modal.data.people} onChange={v=>updateModal('people',v)}/><Choice label="状态" value={modal.data.status} options={['待安排','待确认','待预订','已规划','已确认','备选','时间待核对','日期可调整','待购票']} onChange={v=>updateModal('status',v)}/></>}
{modal.kind==='task'&&<><Field label="待办内容" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><Field label="分类（可自定义）" value={modal.data.category} onChange={v=>updateModal('category',v)}/><Field label="负责人" value={modal.data.owner} onChange={v=>updateModal('owner',v)}/></>}
{modal.kind==='expense'&&<><Field label="费用名称" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><div className="form-grid"><Field label="金额（元）" required min={.01} step="0.01" type="number" value={modal.data.amount||''} onChange={v=>updateModal('amount',Number(v))}/><Field label="发生日期" required type="date" value={modal.data.date} onChange={v=>updateModal('date',v)}/></div><Field label="分类（可自定义）" required value={modal.data.category} onChange={v=>updateModal('category',v)}/><div className="form-grid"><Choice label="付款人" value={modal.data.payer} options={trip.families.flatMap(f=>f.members)} onChange={v=>updateModal('payer',v)}/><Choice label="费用归属" value={modal.data.group} options={['共同',...trip.families.map(f=>f.name)]} onChange={v=>updateModal('group',v)}/></div></>}
{modal.kind==='tip'&&<Field label="提醒标题" required value={modal.data.title} onChange={v=>updateModal('title',v)}/>}
{modal.kind!=='task'&&<label className="field">{modal.kind==='tip'?'提醒内容':'详细信息 / 备注'}<textarea rows={6} value={modal.data.notes} onChange={e=>updateModal('notes',e.target.value)}/></label>}
{editing&&<div className="form-actions"><button type="button" className="btn" onClick={()=>setModal(null)}>取消</button><button type="submit" className="btn primary" disabled={busy}>{busy?'保存中…':'保存'}</button></div>}</fieldset></form>}</DialogContent></Dialog>
<AlertDialog open={!!remove} onOpenChange={open=>!open&&!busy&&setRemove(null)}><AlertDialogContent><AlertDialogTitle>删除这条记录？</AlertDialogTitle><AlertDialogDescription>删除后会同步到家人的页面，其他记录不受影响。</AlertDialogDescription>{error&&<p role="alert" className="error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(remove&&await save({...trip,[remove.kind]:(trip[remove.kind] as {id:string}[]).filter(x=>x.id!==remove.id)}))setRemove(null)}}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</main>}
