'use client';
import {useState,useEffect,useRef} from 'react';
import {Leaf,MapPin,CalendarDays,Wallet,ListChecks,Backpack,Settings,Plus,Pencil,Trash2,ArrowUpRight,Users,Check,Cloud,RefreshCw,ChevronRight,BedDouble,Bookmark,Copy,Utensils,ArrowUp,ArrowDown,Star} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {initialTrip,dateAt,Trip,Event,Task,Expense,Tip,Place,Stay,DayInfo,Cover,normalizeTrip,defaultDay,allPeople,participantLabel,cleanParticipants,placeNames,membersOf,nights,placeCategories,eventCategories,safeUrl} from './trip-data';
import {Field,Choice,Notes,ParticipantPicker,FamilyEditor,PlaceFields,PlacePicker,PlaceDetail,emptyPlace,uid} from './trip-controls';
const tabs=[['plan','每日行程',CalendarDays],['stay','住宿',BedDouble],['places','地点收藏',Bookmark],['money','旅行账本',Wallet],['todo','待办清单',ListChecks],['prepare','行前准备',Backpack],['settings','旅行设置',Settings]] as const;
const money=(n:number)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(n);
type Modal={kind:'event';data:Event}|{kind:'task';data:Task}|{kind:'expense';data:Expense}|{kind:'tip';data:Tip}|{kind:'place';data:Place}|{kind:'stay';data:Stay;place:Place}|{kind:'day';data:DayInfo;day:number}|{kind:'cover';data:Cover}|{kind:'login'};
type Collection='events'|'tasks'|'expenses'|'tips'|'places'|'stays';
type ApiResult={error?:string;trip:Trip;revision:number;updated:string|null;canEdit:boolean};
const collectionFor={event:'events',task:'tasks',expense:'expenses',tip:'tips',place:'places',stay:'stays'} as const;
function put<T extends {id:string}>(list:T[],item:T){return list.some(x=>x.id===item.id)?list.map(x=>x.id===item.id?item:x):[...list,item]}
export default function Home(){
 const [trip,setTrip]=useState<Trip>(initialTrip),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[canEdit,setCanEdit]=useState(false),[editing,setEditing]=useState(false),[tab,setTab]=useState('plan'),[day,setDay]=useState(0),[modal,setModal]=useState<Modal|null>(null),[remove,setRemove]=useState<{kind:Collection;id:string}|null>(null),[key,setKey]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[updated,setUpdated]=useState<string|null>(null),[settings,setSettings]=useState<Trip|null>(null),[filter,setFilter]=useState('全部'),[taskFilter,setTaskFilter]=useState('全部'),[placeFilter,setPlaceFilter]=useState('全部'),[detailId,setDetailId]=useState<string|null>(null),[discard,setDiscard]=useState<null|(()=>void)>(null);
 const busyRef=useRef(false),editingRef=useRef(false),latest=useRef({trip,revision,loaded});latest.current={trip,revision,loaded};editingRef.current=editing;
 const totalPeople=membersOf(trip.families).length,total=trip.expenses.reduce((s,e)=>s+Math.round(e.amount*100),0)/100,done=trip.tasks.filter(t=>t.done).length;
 async function load(silent=false){try{const r=await fetch('/api/trip',{cache:'no-store'}),b=await r.json() as ApiResult;if(!r.ok)throw Error(b.error||'加载失败');if(silent&&(editingRef.current||busyRef.current))return;setTrip(normalizeTrip(b.trip));setRevision(b.revision);setUpdated(b.updated);setCanEdit(b.canEdit);setLoaded(true);if(!silent)setError('')}catch(e){if(!silent)setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(editing||modal)return;const timer=setInterval(()=>{if(!document.hidden&&!busyRef.current)void load(true)},15000);return()=>clearInterval(timer)},[editing,modal]);
 useEffect(()=>{if(day>=trip.days)setDay(trip.days-1)},[trip.days,day]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(editing&&(modal&&modal.kind!=='login'||settings)){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[editing,modal,settings]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!context)return;const ctrl=new AbortController();try{context.registerTool({name:'read_trip_plan',description:'读取当前家庭行程、家人、住宿、地点收藏和待办，不修改数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return latest.current}},{signal:ctrl.signal})}catch{}return()=>ctrl.abort()},[]);
 async function save(next:Trip){if(!editing||busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');try{const r=await fetch('/api/trip',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip:next,revision})}),b=await r.json() as ApiResult;if(!r.ok)throw Error(b.error||'保存失败，输入已保留');setTrip(next);setRevision(b.revision);setUpdated(b.updated);setNotice('已保存，家人的页面会自动更新');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false);busyRef.current=false}}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/editor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})}),b=await r.json() as ApiResult;if(!r.ok)throw Error(b.error||'验证失败');setCanEdit(true);setEditing(true);setModal(null);setKey('');setNotice('已进入编辑模式')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function toggleEdit(){setError('');if(editing){const close=()=>{setEditing(false);setSettings(null)};if(settings)setDiscard(()=>close);else close()}else if(canEdit)setEditing(true);else setModal({kind:'login'})}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('已复制，可粘贴到打车或地图软件')}catch{setError('复制失败，请长按选中地址复制。')}}
 function closeModal(){if(busy)return;const close=()=>{setModal(null);setError('')};if(editing&&modal&&modal.kind!=='login')setDiscard(()=>close);else close()}
 function edit(kind:Modal['kind'],data?:Event|Task|Expense|Tip|Place|Stay){setError('');if(kind==='event')setModal({kind,data:structuredClone(data as Event||{id:uid(),day,time:'',title:'',location:'',people:'',status:'待安排',notes:'',participants:allPeople(),placeIds:[],category:'游览'})});if(kind==='task')setModal({kind,data:structuredClone(data as Task||{id:uid(),title:'',category:'行前',owner:'我',done:false})});if(kind==='expense')setModal({kind,data:structuredClone(data as Expense||{id:uid(),title:'',category:'餐饮',amount:0,date:dateAt(trip.start,day),payer:'',group:'共同',notes:''})});if(kind==='tip')setModal({kind,data:structuredClone(data as Tip||{id:uid(),title:'',notes:''})});if(kind==='place')setModal({kind,data:structuredClone(data as Place||emptyPlace(placeCategories.includes(placeFilter)?placeFilter:'景点'))});if(kind==='stay'){const s=data as Stay|undefined;const p=structuredClone(s?trip.places.find(p=>p.id===s.placeId)||emptyPlace('住宿'):emptyPlace('住宿'));setModal({kind,data:structuredClone(s||{id:uid(),placeId:p.id,checkIn:trip.start,checkOut:dateAt(trip.start,1),room:'',status:'待确认',notes:'',participants:allPeople()}),place:p})}if(kind==='day')setModal({kind,day,data:structuredClone(trip.dayInfo[day])});if(kind==='cover')setModal({kind,data:structuredClone(trip.cover)})}
 function updateModal(prop:string,value:unknown){setModal(m=>m&&m.kind!=='login'?{...m,data:{...m.data,[prop]:value}} as Modal:m)}
 async function submitModal(e:React.FormEvent){e.preventDefault();if(!modal||modal.kind==='login')return;let next={...trip};if(modal.kind==='cover')next.cover=modal.data;else if(modal.kind==='day')next.dayInfo=trip.dayInfo.map((d,i)=>i===modal.day?modal.data:d);else if(modal.kind==='stay'){next.stays=put(trip.stays,modal.data);next.places=put(trip.places,modal.place)}else{const collection=collectionFor[modal.kind];next={...trip,[collection]:put(trip[collection] as {id:string}[],modal.data)}}if(await save(next))setModal(null)}
 async function deleteRecord(){if(!remove)return;const {kind,id}=remove;if(kind==='places'&&trip.stays.some(s=>s.placeId===id)){setError('这处地点仍有关联住宿，请先删除或改选住宿，再删除地点。');return}const next={...trip,[kind]:(trip[kind] as {id:string}[]).filter(x=>x.id!==id)};if(kind==='places'){next.events=trip.events.map(e=>({...e,placeIds:e.placeIds.filter(p=>p!==id)}))}if(await save(next))setRemove(null)}
 async function saveSettings(e:React.FormEvent){e.preventDefault();if(!settings)return;if(settings.days<=Math.max(-1,...trip.events.map(e=>e.day))){setError('缩短天数前，请先移动或删除超出范围的行程。');return}const next={...trip,title:settings.title,start:settings.start,days:settings.days,budget:settings.budget,families:settings.families,dayInfo:Array.from({length:settings.days},(_,i)=>trip.dayInfo[i]||defaultDay(i)),events:trip.events.map(e=>({...e,participants:cleanParticipants(e.participants,settings.families)})),stays:trip.stays.map(s=>({...s,participants:cleanParticipants(s.participants,settings.families)}))};if(await save(next))setSettings(null)}
 function moveEvent(id:string,dir:number){const siblings=trip.events.filter(e=>e.day===day),i=siblings.findIndex(e=>e.id===id),other=siblings[i+dir];if(!other)return;const a=trip.events.findIndex(e=>e.id===id),b=trip.events.findIndex(e=>e.id===other.id),next=[...trip.events];[next[a],next[b]]=[next[b],next[a]];void save({...trip,events:next})}
 function addMeal(category:string){setModal({kind:'event',data:{id:uid(),day,time:category,title:category+' · 餐厅待选',location:'',people:'',status:'待安排',notes:'',participants:allPeople(),placeIds:[],category}})}
 const actions=(kind:'event'|'task'|'expense'|'tip'|'place'|'stay',data:{id:string;title?:string;name?:string})=><span className="actions"><button disabled={busy} aria-label={'编辑'+(data.title||data.name||'住宿')} onClick={()=>edit(kind,data as Event)}><Pencil size={16}/></button><button disabled={busy} aria-label={'删除'+(data.title||data.name||'住宿')} onClick={()=>{setError('');setRemove({kind:collectionFor[kind],id:data.id})}}><Trash2 size={16}/></button></span>;
 const dayEvents=trip.events.filter(e=>e.day===day),today=dateAt(trip.start,day),dayStays=trip.stays.filter(s=>s.checkIn<=today&&s.checkOut>today),dayData=trip.dayInfo[day]||defaultDay(day);
 const currentPlace=trip.places.find(p=>p.id===detailId)||null;
 const linkedPlaces=(ids:string[])=>ids.map(id=>trip.places.find(p=>p.id===id)).filter((p):p is Place=>!!p);
 const placeCard=(p:Place)=><article className="place-card" key={p.id}><div className="between"><span className="badge">{p.category} · {p.status}</span>{p.favorite&&<Star size={17}/>}</div><button className="place-card-title" onClick={()=>setDetailId(p.id)}>{p.name}<ArrowUpRight size={17}/></button><p className="place-description">{p.description||'介绍待补充'}</p><div className="place-address"><MapPin size={15}/><span>{p.address||'详细地址待补充'}</span></div><div className="between"><button className="btn small" disabled={!p.address} onClick={()=>copy(p.address)}><Copy size={14}/>复制地址</button>{editing?actions('place',p):<button className="text-button" onClick={()=>setDetailId(p.id)}>查看详情 →</button>}</div></article>;
 return <main className="shell"><header><div className="brand"><span className="brand-icon"><Leaf size={24}/></span><div><b>{trip.title}</b><small>{trip.cover.subtitle}</small></div></div><div className="top-actions"><span className="sync"><Cloud size={15}/>{loaded?'共享云端':'连接中'}</span><button className={editing?'btn primary':'btn'} disabled={!loaded||busy} onClick={toggleEdit}>{editing?<Check size={16}/>:<Pencil size={16}/>} {editing?'完成编辑':'编辑攻略'}</button></div></header>
 <section className="hero"><div><div className="eyebrow">{trip.cover.kicker}</div><h1>{trip.cover.headline}</h1><p>{trip.cover.route}</p><div className="hero-chips"><span><CalendarDays size={15}/>{trip.start.replaceAll('-','.')} — {dateAt(trip.start,trip.days-1).slice(5).replace('-','.')}</span><span><Users size={15}/>{totalPeople} 位家人 · {trip.families.length} 个家庭</span></div><p className="cover-note">{trip.cover.note}</p></div>{editing&&<button className="btn cover-edit" onClick={()=>edit('cover')}><Pencil size={14}/>编辑封面文字</button>}</section>
 <div className="overview"><div><strong>{String(trip.days).padStart(2,'0')}</strong><span>天的旅行计划</span></div><div><strong>{String(trip.places.length).padStart(2,'0')}</strong><span>个收藏地点</span></div><div><strong>{done}<i> / {trip.tasks.length}</i></strong><span>项准备已完成</span></div><div><strong>{money(total)}</strong><span>实际支出 · 人均 {money(total/Math.max(totalPeople,1))}</span></div></div>
 {editing&&<div className="edit-banner"><Pencil size={16}/><span>编辑模式 · 点击铅笔修改资料，保存后同步给家人</span><button disabled={busy} onClick={()=>{const run=async()=>{try{const r=await fetch('/api/editor',{method:'DELETE'});if(!r.ok)throw Error('退出失败');setEditing(false);setCanEdit(false);setSettings(null)}catch{setError('退出失败，请重试')}};if(settings)setDiscard(()=>run);else void run()}}>退出编辑权限</button></div>}
 {error&&!modal&&!remove&&<div role="alert" className="error">{error}<button className="btn" onClick={()=>{if(settings)setDiscard(()=>()=>{setSettings(null);void load()});else void load()}}>重新载入</button></div>}{notice&&<div role="status" className="toast"><Check size={16}/>{notice}</div>}
 <Tabs value={tab} onValueChange={v=>{setTab(v);setFilter('全部')}}><TabsList className="main-tabs">{tabs.map(([id,label,Icon])=><TabsTrigger key={id} value={id}><Icon size={18}/><span>{label}</span></TabsTrigger>)}</TabsList>
 <TabsContent value="plan"><div className="trip-layout"><aside className="day-nav"><p className="eyebrow">这趟旅程</p>{Array.from({length:trip.days},(_,i)=><button key={i} className={day===i?'day-button selected':'day-button'} onClick={()=>setDay(i)}><span className="day-index">{String(i+1).padStart(2,'0')}</span><span><b>{dateAt(trip.start,i).slice(5).replace('-',' 月 ')} 日</b><small>{trip.dayInfo[i]?.region||'待安排'}</small></span><ChevronRight size={16}/></button>)}<div className="aside-note"><BedDouble size={20}/><b>{dayStays.length?'这晚住这里':'本晚住宿尚未安排'}</b>{dayStays.map(s=><button className="text-button" key={s.id} onClick={()=>setTab('stay')}>{trip.places.find(p=>p.id===s.placeId)?.name} →</button>)}</div></aside><section className="itinerary"><div className="section-heading"><div><span className="eyebrow">DAY {String(day+1).padStart(2,'0')} / {today}</span><h2>{dayData.title}</h2></div>{editing&&<div className="heading-actions"><button className="btn" onClick={()=>edit('day')} aria-label="编辑当日标题与备注"><Pencil size={15}/></button><button className="btn primary" onClick={()=>edit('event')}><Plus size={16}/>添加行程</button></div>}</div>{dayData.note&&<p className="muted prewrap">{dayData.note}</p>}
 <div className="meal-strip">{['早餐','午餐','晚餐'].map(meal=>{const found=dayEvents.filter(e=>e.category===meal);return <div key={meal}><span><Utensils size={14}/>{meal}</span>{found.length?found.map(e=><button key={e.id} onClick={()=>edit('event',e)}>{e.title}</button>):<button disabled={!editing} onClick={()=>addMeal(meal)}>{editing?'＋ 安排这一餐':'还没安排'}</button>}</div>})}</div>
 <div className="timeline">{dayEvents.length?dayEvents.map((e,i)=><article className="event" key={e.id}><div className="event-marker">{String(i+1).padStart(2,'0')}</div><div className="event-body"><div className="event-top"><span>{e.time||'时间待定'} · {e.category}</span><span className={'badge '+(e.status==='已确认'?'confirmed':'')}>{e.status}</span></div><button className="event-title" onClick={()=>edit('event',e)}>{e.title}<ArrowUpRight size={17}/></button><p><Users size={14}/>{participantLabel(e.participants,trip.families)}</p>{e.participants.note&&<small className="participant-note">{e.participants.note}</small>}<p><MapPin size={14}/>{placeNames(e,trip)}</p>{e.placeIds.length>0&&<div className="event-place-links">{linkedPlaces(e.placeIds).map(p=><button key={p.id} onClick={()=>setDetailId(p.id)}>{p.name}<ArrowUpRight size={13}/></button>)}</div>}{editing&&<div className="between event-tools"><span className="actions"><button aria-label={'上移'+e.title} disabled={busy||i===0} onClick={()=>moveEvent(e.id,-1)}><ArrowUp size={15}/></button><button aria-label={'下移'+e.title} disabled={busy||i===dayEvents.length-1} onClick={()=>moveEvent(e.id,1)}><ArrowDown size={15}/></button></span>{actions('event',e)}</div>}</div></article>):<div className="empty">这一天还没有行程，留一点时间自由探索。</div>}</div></section></div></TabsContent>
 <TabsContent value="stay"><div className="section-heading"><div><span className="eyebrow">OUR LITTLE HOME</span><h2>落脚的地方，记在这里。</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('stay')}><Plus size={16}/>添加住宿</button>}</div><p className="muted">住宿名称和地址与地点收藏共用一份资料，修改一次，行程里也会更新。</p><div className="stay-grid">{trip.stays.map(s=>{const p=trip.places.find(p=>p.id===s.placeId);return <article className="panel stay-card" key={s.id}><div className="between"><span className="badge">{s.status}</span><span className="night-count">{nights(s.checkIn,s.checkOut)} 晚</span></div><h3>{p?.name||'住宿地点待补充'}</h3><div className="stay-dates"><div><small>入住</small><b>{s.checkIn}</b></div><span>→</span><div><small>退房</small><b>{s.checkOut}</b></div></div><p><Users size={15}/>{participantLabel(s.participants,trip.families)}</p>{s.participants.note&&<p>{s.participants.note}</p>}<p>{s.room||'房型待补充'}</p><div className="address-box"><MapPin size={19}/><div><b>民宿 / 酒店地址</b><p>{p?.address||'还没有填写地址'}</p><button className="btn small" disabled={!p?.address} onClick={()=>copy(p?.address||'')}><Copy size={14}/>复制地址</button></div></div>{p?.phone&&<p>联系电话：{p.phone}</p>}<p className="prewrap muted">{s.notes}</p><div className="between"><button className="text-button" onClick={()=>setDetailId(s.placeId)}>查看住宿详情 ↗</button>{editing&&<><button className="btn" onClick={()=>edit('stay',s)}><Pencil size={15}/>编辑住宿与地址</button><button className="icon-button" aria-label={'删除住宿'+p?.name} onClick={()=>setRemove({kind:'stays',id:s.id})}><Trash2 size={16}/></button></>}</div></article>})}</div>{!trip.stays.length&&<section className="panel empty"><BedDouble size={32}/><h3>今晚，住在哪里？</h3><p>进入编辑模式添加民宿或酒店。</p></section>}</TabsContent>
 <TabsContent value="places"><div className="section-heading"><div><span className="eyebrow">PLACES TO KEEP</span><h2>想去的、想吃的，都收藏好。</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('place')}><Plus size={16}/>添加地点 / 店铺</button>}</div><div className="filters">{['全部','必去 / 必吃',...placeCategories].map(c=><button key={c} className={placeFilter===c?'chip active':'chip'} onClick={()=>setPlaceFilter(c)}>{c}</button>)}</div><div className="places-grid">{trip.places.filter(p=>placeFilter==='全部'||placeFilter==='必去 / 必吃'&&p.favorite||p.category===placeFilter).map(placeCard)}</div>{!trip.places.filter(p=>placeFilter==='全部'||placeFilter==='必去 / 必吃'&&p.favorite||p.category===placeFilter).length&&<section className="panel empty"><Bookmark size={32}/><h3>{placeFilter==='旅拍'?'把心仪的旅拍店放进候选清单':placeFilter==='餐厅'?'下一顿，想吃什么？':'这里还没有收藏'}</h3><p>添加真实店名、地址、介绍与套餐后，可以在行程里多选比较。</p>{editing&&<button className="btn" onClick={()=>edit('place')}>添加第一家</button>}</section>}</TabsContent>
 <TabsContent value="money"><div className="section-heading"><div><span className="eyebrow">TRAVEL EXPENSES</span><h2>旅行账本</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('expense')}><Plus size={16}/>记一笔</button>}</div><div className="money-summary"><section className="panel"><small>累计实际支出</small><h2>{money(total)}</h2><p>预算 {trip.budget?money(trip.budget):'未设置'}{trip.budget>0&&' · 剩余 '+money(trip.budget-total)}</p></section><section className="panel"><small>按费用归属统计</small>{[...new Set(trip.expenses.map(e=>e.familyId?trip.families.find(f=>f.id===e.familyId)?.name||e.group:e.group)),...['共同',...trip.families.map(f=>f.name)].filter(g=>!trip.expenses.some(e=>(e.familyId?trip.families.find(f=>f.id===e.familyId)?.name||e.group:e.group)===g))].map(g=><p className="between" key={g}><span>{g}</span><b>{money(trip.expenses.filter(e=>(e.familyId?trip.families.find(f=>f.id===e.familyId)?.name||e.group:e.group)===g).reduce((s,e)=>s+Math.round(e.amount*100),0)/100)}</b></p>)}<small>人均仅作参考，不代表两家结算金额。</small></section></div><div className="filters">{['全部',...new Set(trip.expenses.map(e=>e.category))].map(c=><button key={c} className={filter===c?'chip active':'chip'} onClick={()=>setFilter(c)}>{c}</button>)}</div><section className="panel">{trip.expenses.filter(e=>filter==='全部'||e.category===filter).map(e=><article key={e.id} className="expense"><span className="expense-icon"><Wallet size={20}/></span><div><b>{e.title}</b><small>{e.date} · {e.category} · {membersOf(trip.families).find(m=>m.id===e.payerId)?.name||e.payer||'付款人待定'}付款 · {trip.families.find(f=>f.id===e.familyId)?.name||e.group}</small>{e.notes&&<p>{e.notes}</p>}</div><strong>{money(e.amount)}</strong>{editing&&actions('expense',e)}</article>)}{!trip.expenses.filter(e=>filter==='全部'||e.category===filter).length&&<div className="empty"><Wallet size={36}/><h3>这里还没有支出记录</h3><p>记录实际花费，预订计划放在待办里。</p></div>}</section></TabsContent>
 <TabsContent value="todo"><div className="section-heading"><div><span className="eyebrow">BEFORE WE GO</span><h2>待办清单</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('task')}><Plus size={16}/>添加待办</button>}</div><section className="panel"><div className="between"><b>准备进度</b><span>{done} / {trip.tasks.length} 已完成</span></div><Progress className="my-4 h-2" value={trip.tasks.length?done/trip.tasks.length*100:0}/><div className="filters">{['全部','未完成','已完成'].map(c=><button key={c} className={taskFilter===c?'chip active':'chip'} onClick={()=>setTaskFilter(c)}>{c}</button>)}</div>{!editing&&<p className="muted">进入编辑模式可勾选完成事项。</p>}{trip.tasks.filter(t=>taskFilter==='全部'||t.done===(taskFilter==='已完成')).map(t=><div className="task" key={t.id}><Checkbox aria-label={'完成：'+t.title} checked={t.done} disabled={!editing||busy} onCheckedChange={v=>save({...trip,tasks:trip.tasks.map(x=>x.id===t.id?{...x,done:v===true}:x)})}/><div><span className={t.done?'completed':''}>{t.title}</span><small>{t.category} · {t.owner||'未分配'}</small></div>{editing&&actions('task',t)}</div>)}</section></TabsContent>
 <TabsContent value="prepare"><div className="section-heading"><div><span className="eyebrow">PACK LIGHT, PLAN WELL</span><h2>行前准备</h2></div>{editing&&<button className="btn primary" onClick={()=>edit('tip')}><Plus size={16}/>添加提醒</button>}</div><div className="tips-grid">{trip.tips.map((t,i)=><section className="panel" key={t.id}><span className="tip-number">{String(i+1).padStart(2,'0')}</span><h3>{t.title}</h3><p className="prewrap">{t.notes}</p>{t.url&&safeUrl(t.url)&&<a href={safeUrl(t.url)} target="_blank" rel="noreferrer">查看相关信息 ↗</a>}{editing&&actions('tip',t)}</section>)}</div></TabsContent>
 <TabsContent value="settings"><div className="section-heading"><div><span className="eyebrow">OUR TRIP</span><h2>旅行总设置</h2></div></div><section className="panel"><form onSubmit={saveSettings}><fieldset disabled={!editing||busy}><div className="form-grid"><Field label="旅行名称" required value={(settings||trip).title} onChange={v=>setSettings({...settings||trip,title:v})}/><Field label="起始日期" required type="date" value={(settings||trip).start} onChange={v=>setSettings({...settings||trip,start:v})}/><Field label="旅行总天数" type="number" required min={1} max={30} value={(settings||trip).days} onChange={v=>setSettings({...settings||trip,days:Number(v)})}/><Field label="总预算（元，0 为未设置）" type="number" min={0} step="0.01" value={(settings||trip).budget} onChange={v=>setSettings({...settings||trip,budget:Number(v)})}/></div><p className="muted">修改起始日期会移动每日行程；住宿入住退房日期和账目日期保留实际日期，请按订单单独核对。</p><h3>同行的家人</h3><FamilyEditor disabled={!editing||busy} families={(settings||trip).families} onChange={families=>setSettings({...settings||trip,families})}/><p className="muted">成员改名会更新关联行程。移除成员或家庭后，保存时会从参与名单中一并移除；账目的历史付款记录保留。</p>{editing&&<div className="form-actions"><button className="btn" type="button" disabled={!settings} onClick={()=>setDiscard(()=>()=>setSettings(null))}>放弃修改</button><button className="btn primary" type="submit" disabled={!settings||busy}>{busy?'保存中…':'保存旅行设置'}</button></div>}</fieldset></form><p className="muted">共 {membersOf((settings||trip).families).length} 位成员 · 人数自动联动概览与人均支出。</p></section><section className="panel"><h3>封面与每日文字</h3><p>封面标题、副标题、路线、寄语可编辑；每天的标题、地区和备注可在每日行程的铅笔按钮中修改。</p>{editing&&<button className="btn" onClick={()=>edit('cover')}>编辑封面文字</button>}</section><section className="panel"><h3>共享与更新</h3><p>保存后，家人的查看页面每 15 秒检查更新。编辑中的页面不会自动覆盖草稿。</p><button className="btn" onClick={()=>copy(location.origin)}>复制查看链接</button></section></TabsContent></Tabs>
 <footer><span>{updated?'最近保存 '+new Date(updated).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})+'（北京时间）':'旅行手账 · 待确认内容请按订单核实'}</span><button disabled={busy||editing} onClick={()=>load()}><RefreshCw size={13}/>刷新</button><div>秋日手绘插画 · 示意画面，非景区实景</div></footer>
 <Dialog open={!!modal} onOpenChange={open=>!open&&closeModal()}><DialogContent className="trip-dialog"><DialogTitle>{modal?.kind==='login'?'解锁编辑模式':modal?.kind==='event'?'行程详情':modal?.kind==='task'?'待办事项':modal?.kind==='expense'?'记录支出':modal?.kind==='place'?'地点 / 店铺资料':modal?.kind==='stay'?'住宿与地址':modal?.kind==='day'?'这一天的标题与备注':modal?.kind==='cover'?'封面文字':'行前提醒'}</DialogTitle><DialogDescription>{modal?.kind==='login'?'输入你的专属编辑口令。':editing?'修改后点击保存，同步给家人。':'查看模式 · 进入编辑模式可以修改。'}</DialogDescription>{error&&<div role="alert" className="error">{error}</div>}
 {modal?.kind==='login'?<form onSubmit={login}><Field label="编辑口令" type="password" required value={key} onChange={setKey}/><button className="btn primary mt-4" disabled={busy}>{busy?'验证中…':'进入编辑模式'}</button></form>:modal&&<>
 {!editing&&modal.kind==='event'?<div className="read-event"><span className="badge">{modal.data.status}</span><h3>{modal.data.title}</h3><p>{dateAt(trip.start,modal.data.day)} · {modal.data.time||'时间待定'} · {modal.data.category}</p><h4>参与家人</h4><p>{participantLabel(modal.data.participants,trip.families)}</p><p>{modal.data.participants.note}</p><h4>行程安排</h4><p className="prewrap">{modal.data.notes||'暂无补充说明'}</p>{modal.data.location&&<p>地点补充：{modal.data.location}</p>}<h4>地点与候选店铺</h4>{linkedPlaces(modal.data.placeIds).map(p=><div className="linked-place" key={p.id}><button className="text-button" onClick={()=>setDetailId(p.id)}>{p.name} ↗</button><p>{p.address||'详细地址待补充'}</p><button className="btn small" disabled={!p.address} onClick={()=>copy(p.address)}><Copy size={14}/>复制地址</button></div>)}</div>:<form onSubmit={submitModal}><fieldset disabled={!editing||busy}>
 {modal.kind==='event'&&<><Field label="活动名称" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><div className="form-grid"><Choice label="旅行第几天" value={String(modal.data.day+1)} options={Array.from({length:trip.days},(_,i)=>String(i+1))} onChange={v=>updateModal('day',Number(v)-1)}/><Field label="时间 / 时段" value={modal.data.time} onChange={v=>updateModal('time',v)}/><Choice label="活动分类" value={modal.data.category} options={[...new Set([modal.data.category,...eventCategories])]} onChange={v=>updateModal('category',v)}/><Field label="状态" required value={modal.data.status} onChange={v=>updateModal('status',v)}/></div><ParticipantPicker value={modal.data.participants} families={trip.families} onChange={p=>updateModal('participants',p)}/><PlacePicker places={trip.places} selected={modal.data.placeIds} onChange={ids=>updateModal('placeIds',ids)} onDetail={setDetailId}/><Field label="地点补充（路线、集合点等）" value={modal.data.location} onChange={v=>updateModal('location',v)}/><Notes label="详细安排 / 备注" value={modal.data.notes} onChange={v=>updateModal('notes',v)}/></>}
 {modal.kind==='place'&&<PlaceFields place={modal.data} onChange={p=>setModal({...modal,data:p})}/>}
 {modal.kind==='stay'&&<><Choice label="选择已有住宿 / 当前资料" value={modal.place.id} options={[{value:modal.place.id,label:modal.place.name||'新住宿'},...trip.places.filter(p=>p.category==='住宿'&&p.id!==modal.place.id).map(p=>({value:p.id,label:p.name}))]} onChange={id=>{const p=trip.places.find(x=>x.id===id);if(p)setModal({...modal,place:structuredClone(p),data:{...modal.data,placeId:p.id}})}}/><div className="form-grid"><Field label="入住日期" type="date" required value={modal.data.checkIn} onChange={v=>updateModal('checkIn',v)}/><Field label="退房日期" type="date" required value={modal.data.checkOut} onChange={v=>updateModal('checkOut',v)}/></div><Field label="房型 / 房间分配" value={modal.data.room} onChange={v=>updateModal('room',v)}/><Field label="住宿预订状态" required value={modal.data.status} onChange={v=>updateModal('status',v)}/><ParticipantPicker value={modal.data.participants} families={trip.families} onChange={p=>updateModal('participants',p)}/><Notes label="本次住宿备注" value={modal.data.notes} onChange={v=>updateModal('notes',v)}/><hr/><h3>住宿地点资料</h3><p className="muted">以下修改会同步到关联的行程与地点收藏。</p><PlaceFields category={false} place={modal.place} onChange={p=>setModal({...modal,place:p})}/></>}
 {modal.kind==='day'&&<><Field label="当日标题" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><Field label="地区标签" value={modal.data.region} onChange={v=>updateModal('region',v)}/><Notes label="当日备注" value={modal.data.note} onChange={v=>updateModal('note',v)}/></>}
 {modal.kind==='cover'&&<><Field label="主标题" required value={modal.data.headline} onChange={v=>updateModal('headline',v)}/><Field label="顶部副标题" value={modal.data.subtitle} onChange={v=>updateModal('subtitle',v)}/><Field label="封面眉题" value={modal.data.kicker} onChange={v=>updateModal('kicker',v)}/><Field label="旅行路线" value={modal.data.route} onChange={v=>updateModal('route',v)}/><Notes label="封面寄语" value={modal.data.note} onChange={v=>updateModal('note',v)}/></>}
 {modal.kind==='task'&&<><Field label="待办内容" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><Field label="分类" value={modal.data.category} onChange={v=>updateModal('category',v)}/><Field label="负责人 / 备注" value={modal.data.owner} onChange={v=>updateModal('owner',v)}/></>}
 {modal.kind==='expense'&&<><Field label="费用名称" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><div className="form-grid"><Field label="金额（元）" required min={.01} step="0.01" type="number" value={modal.data.amount||''} onChange={v=>updateModal('amount',Number(v))}/><Field label="发生日期" required type="date" value={modal.data.date} onChange={v=>updateModal('date',v)}/></div><Field label="分类" required value={modal.data.category} onChange={v=>updateModal('category',v)}/><div className="form-grid"><Choice label="付款人" value={modal.data.payerId||''} options={[{value:'',label:modal.data.payer||'待确认'},...membersOf(trip.families).map(m=>({value:m.id,label:m.name}))]} onChange={id=>setModal({...modal,data:{...modal.data,payerId:id||undefined,payer:membersOf(trip.families).find(m=>m.id===id)?.name||modal.data.payer}})}/><Choice label="费用归属" value={modal.data.familyId||''} options={[{value:'',label:modal.data.familyId?'共同':modal.data.group||'共同'},...trip.families.map(f=>({value:f.id,label:f.name}))]} onChange={id=>setModal({...modal,data:{...modal.data,familyId:id||undefined,group:trip.families.find(f=>f.id===id)?.name||'共同'}})}/></div><Notes label="费用备注" value={modal.data.notes} onChange={v=>updateModal('notes',v)}/></>}
 {modal.kind==='tip'&&<><Field label="提醒标题" required value={modal.data.title} onChange={v=>updateModal('title',v)}/><Notes label="提醒内容" rows={6} value={modal.data.notes} onChange={v=>updateModal('notes',v)}/><Field label="相关信息链接" type="url" value={modal.data.url||''} onChange={v=>updateModal('url',v)}/></>}
 {editing&&<div className="form-actions"><button type="button" className="btn" onClick={closeModal}>取消</button><button type="submit" className="btn primary" disabled={busy}>{busy?'保存中…':'保存'}</button></div>}</fieldset></form>}</>}
 </DialogContent></Dialog>
 <PlaceDetail place={currentPlace} onClose={()=>setDetailId(null)} onEdit={p=>edit('place',p)} editing={editing&&!modal} copy={copy}/>
 <AlertDialog open={!!remove} onOpenChange={open=>!open&&!busy&&setRemove(null)}><AlertDialogContent><AlertDialogTitle>删除这条记录？</AlertDialogTitle><AlertDialogDescription>{remove?.kind==='places'?'删除地点会同时解除行程中的关联。有关联住宿的地点需要先处理住宿记录。':'删除后会同步到家人的页面。删除住宿安排会保留地点资料，可在地点收藏中另行管理。'}</AlertDialogDescription>{error&&<p role="alert" className="error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void deleteRecord()}}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!discard} onOpenChange={open=>!open&&setDiscard(null)}><AlertDialogContent><AlertDialogTitle>放弃尚未保存的修改？</AlertDialogTitle><AlertDialogDescription>已保存的内容保持不变，当前表单的修改将不保留。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>继续编辑</AlertDialogCancel><AlertDialogAction onClick={()=>{discard?.();setDiscard(null)}}>放弃修改</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
