'use client';
import {useEffect,useState} from 'react';
import {CloudSun,Sun,Cloud,CloudFog,CloudRain,CloudSnow,CloudLightning,RefreshCw,Upload,ImageIcon,X} from 'lucide-react';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Media} from './trip-data';
import {Choice} from './trip-controls';
export function WeatherBar(){const [area,setArea]=useState('mountain'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tick,setTick]=useState(0);useEffect(()=>{const c=new AbortController();setData(null);setLoading(true);setError('');fetch('/api/weather?area='+area,{signal:c.signal}).then(async r=>{const b=await r.json() as any;if(!r.ok)throw Error(b.error);setData(b)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[area,tick]);useEffect(()=>{const t=setInterval(()=>{if(!document.hidden)setTick(v=>v+1)},600000);return()=>clearInterval(t)},[]);const c=data?.current;const code=c?.weather_code;const desc=code===0?'晴':code<=3?'晴间多云':code<=48?'雾':code<=67?'雨':code<=77?'雪':code<=82?'阵雨':code<=86?'阵雪':code>=95?'雷暴':'天气';const stale=c&&Date.now()-Date.parse(c.time+'+08:00')>3*3600000;const Icon=code===0?Sun:code<=3?CloudSun:code<=48?CloudFog:code<=67?CloudRain:code<=77?CloudSnow:code<=82?CloudRain:code<=86?CloudSnow:code>=95?CloudLightning:Cloud;return <Popover><PopoverTrigger asChild><button className="weather-mini" aria-label={(area==='mountain'?'长白山北景区':'二道白河镇')+'天气，点击切换区域'} title={desc+' · 点击切换区域'}><Icon size={20}/><span>{loading?'…':error?'--':c?Math.round(c.temperature_2m)+'°':'…'}</span></button></PopoverTrigger><PopoverContent className="weather-popover"><Choice label="天气区域" value={area} options={[{value:'mountain',label:'长白山北景区'},{value:'town',label:'二道白河镇'}]} onChange={setArea}/><div aria-live="polite">{loading?'正在更新…':error||c&&<p>{desc} · {Math.round(c.temperature_2m)}°C · 体感 {Math.round(c.apparent_temperature)}°C<br/>风速 {c.wind_speed_10m} m/s</p>}</div><button className="btn small" disabled={loading} onClick={()=>setTick(v=>v+1)}><RefreshCw size={14}/>刷新天气</button><p className="weather-source">{c?`${stale?'数据较旧 · ':''}${c.time.replace('T',' ')} 北京时间 · `:''}<a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> 当前模型估算，非现场实测。{area==='mountain'?'天池附近参考，开放情况以官方公告为准。':'镇内参考，不代表山顶天气。'}</p></PopoverContent></Popover>}

export function MediaUpload({value,onChange,multiple=false,onBusy}:{value:Media[];onChange:(m:Media[])=>void;multiple?:boolean;onBusy?:(b:boolean)=>void}){const [working,setWorking]=useState(false),[error,setError]=useState('');async function upload(files:FileList|null){if(!files?.length)return;setWorking(true);onBusy?.(true);setError('');let next=multiple?[...value]:[];try{for(const file of Array.from(files).slice(0,multiple?8-value.length:1)){if(file.size>5*1024*1024)throw Error('每张图片最多 5 MB');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('请选择 JPG、PNG 或 WebP 图片');const res=await fetch('/api/media',{method:'POST',headers:{'Content-Type':file.type},body:file});const b=await res.json() as {id:string;error?:string};if(!res.ok)throw Error(b.error||'上传失败');next=[...next,{id:b.id,name:file.name}];onChange(next)}}catch(e){setError((e as Error).message)}finally{setWorking(false);onBusy?.(false)}}return <div className="media-upload"><div className="media-thumbs">{value.map(m=><div key={m.id}><a href={'/api/media/'+m.id} target="_blank" rel="noreferrer"><img src={'/api/media/'+m.id} alt={m.name}/></a><button type="button" disabled={working} aria-label={'移除图片'+m.name} onClick={()=>onChange(value.filter(x=>x.id!==m.id))}><X size={14}/></button></div>)}</div><label className="btn upload-button"><Upload size={15}/>{working?'上传中…':multiple?'上传消费截图':'上传景区内部地图'}<input type="file" accept="image/png,image/jpeg,image/webp" multiple={multiple} disabled={working||(multiple&&value.length>=8)} onChange={e=>{void upload(e.target.files);e.target.value=''}}/></label><small>JPG / PNG / WebP，每张不超过 5 MB{multiple?'，最多 8 张':''}。保存记录后，拿到网页链接的家人可查看。</small>{error&&<p role="alert" className="error">{error}</p>}</div>}
export function MediaGallery({items}:{items:Media[]}){return items.length?<div className="receipt-gallery">{items.map(m=><a key={m.id} href={'/api/media/'+m.id} target="_blank" rel="noreferrer"><img src={'/api/media/'+m.id} alt={m.name}/><span>打开原图 ↗</span></a>)}</div>:<p className="muted"><ImageIcon size={17}/> 暂无消费截图</p>}
