'use client';
import {useEffect,useState} from 'react';
import {CloudSun,Sun,Cloud,CloudFog,CloudRain,CloudSnow,CloudLightning,RefreshCw,Upload,ImageIcon,X} from 'lucide-react';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Media} from './trip-data';
import {weatherAreas,WeatherArea,WeatherResult} from './weather-data';
import {Choice} from './trip-controls';
export function WeatherBar(){
 const [area,setArea]=useState<WeatherArea>('town'),[data,setData]=useState<WeatherResult|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>{let active=true;const c=new AbortController();setData(null);setLoading(true);setError('');const timer=setTimeout(()=>c.abort(),15000);fetch('/api/weather?area='+area,{signal:c.signal}).then(async r=>{const b=await r.json() as WeatherResult;if(!r.ok)throw Error(b.error||'天气暂时无法更新');if(active)setData(b)}).catch(()=>{if(active)setError('天气暂时无法更新，请查看中国天气网。')}).finally(()=>{clearTimeout(timer);if(active)setLoading(false)});return()=>{active=false;clearTimeout(timer);c.abort()}},[area,tick]);
 useEffect(()=>{const t=setInterval(()=>{if(!document.hidden)setTick(v=>v+1)},600000);return()=>clearInterval(t)},[]);
 const desc=data?.description||'';const Icon=/雷/.test(desc)?CloudLightning:/雪/.test(desc)?CloudSnow:/雨/.test(desc)?CloudRain:/雾|霾|尘/.test(desc)?CloudFog:desc==='晴'?Sun:/云/.test(desc)?CloudSun:Cloud;
 return <Popover><PopoverTrigger asChild><button className="weather-mini" aria-label={weatherAreas[area].label+'天气，点击切换区域'} title={data?.reference||weatherAreas[area].label}><Icon size={20}/><span>{loading?'…':data?.temperature!==undefined?Math.round(data.temperature)+'°':'--'}</span></button></PopoverTrigger><PopoverContent className="weather-popover"><Choice label="天气区域" value={area} options={[{value:'mountain',label:'长白山北景区'},{value:'town',label:'二道白河区域 · 安图县参考'}]} onChange={v=>setArea(v as WeatherArea)}/><div aria-live="polite">{loading?'正在更新…':error||data?.error||<><p>{desc} · {data?.temperature}°C<br/>{data?.wind}</p><p className="muted">{data?.reference}</p></>}</div><button className="btn small" disabled={loading} onClick={()=>setTick(v=>v+1)}><RefreshCw size={14}/>刷新天气</button><p><a href={weatherAreas[area].url} target="_blank" rel="noreferrer">中国天气网 · {weatherAreas[area].label}预报 ↗</a></p>{data?.temperature!==undefined&&<p className="weather-source">数据提供：<a href="https://uapis.cn/docs/api-reference/get-misc-weather" target="_blank" rel="noreferrer">UAPI</a> · {data.reportTime}<br/>查询于 {new Date(data.fetchedAt!).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}（北京时间）。县域天气不代表镇内或山顶天气。</p>}</PopoverContent></Popover>
}

export function MediaUpload({value,onChange,multiple=false,onBusy}:{value:Media[];onChange:(m:Media[])=>void;multiple?:boolean;onBusy?:(b:boolean)=>void}){const [working,setWorking]=useState(false),[error,setError]=useState('');async function upload(files:FileList|null){if(!files?.length)return;setWorking(true);onBusy?.(true);setError('');let next=multiple?[...value]:[];try{for(const file of Array.from(files).slice(0,multiple?8-value.length:1)){if(file.size>5*1024*1024)throw Error('每张图片最多 5 MB');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('请选择 JPG、PNG 或 WebP 图片');const res=await fetch('/api/media',{method:'POST',headers:{'Content-Type':file.type},body:file});const b=await res.json() as {id:string;error?:string};if(!res.ok)throw Error(b.error||'上传失败');next=[...next,{id:b.id,name:file.name}];onChange(next)}}catch(e){setError((e as Error).message)}finally{setWorking(false);onBusy?.(false)}}return <div className="media-upload"><div className="media-thumbs">{value.map(m=><div key={m.id}><a href={'/api/media/'+m.id} target="_blank" rel="noreferrer"><img src={'/api/media/'+m.id} alt={m.name}/></a><button type="button" disabled={working} aria-label={'移除图片'+m.name} onClick={()=>onChange(value.filter(x=>x.id!==m.id))}><X size={14}/></button></div>)}</div><label className="btn upload-button"><Upload size={15}/>{working?'上传中…':multiple?'上传消费截图':'上传景区内部地图'}<input type="file" accept="image/png,image/jpeg,image/webp" multiple={multiple} disabled={working||(multiple&&value.length>=8)} onChange={e=>{void upload(e.target.files);e.target.value=''}}/></label><small>JPG / PNG / WebP，每张不超过 5 MB{multiple?'，最多 8 张':''}。保存记录后，拿到网页链接的家人可查看。</small>{error&&<p role="alert" className="error">{error}</p>}</div>}
export function MediaGallery({items}:{items:Media[]}){return items.length?<div className="receipt-gallery">{items.map(m=><a key={m.id} href={'/api/media/'+m.id} target="_blank" rel="noreferrer"><img src={'/api/media/'+m.id} alt={m.name}/><span>打开原图 ↗</span></a>)}</div>:<p className="muted"><ImageIcon size={17}/> 暂无消费截图</p>}
