'use client';
import {useId,useState} from 'react';
import {MediaUpload} from './trip-extras';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Map,Plus,Trash2,Users,Copy,MapPin,ExternalLink,Star} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Family,Participants,participantIds,participantLabel,membersOf,Place,safeUrl,placeCategories,defaultCategoryLabels} from './trip-data';
import {priceLabels} from './trip-features';
export const uid=()=>crypto.randomUUID();
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string}){const options2=options.map(o=>typeof o==='string'?{value:o,label:o}:o);return <label className="field">{label}<Select value={value||'__none'} onValueChange={v=>{if(v)onChange(v==='__none'?'':v)}}><SelectTrigger><SelectValue>{options2.find(o=>o.value===value)?.label}</SelectValue></SelectTrigger><SelectContent>{options2.map(o=><SelectItem key={o.value||'__none'} value={o.value||'__none'}>{o.label}</SelectItem>)}</SelectContent></Select></label>}
export function Field({label,value,onChange,type='text',required=false,min,max,step}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string;required?:boolean;min?:number;max?:number;step?:string}){return <label className="field">{label}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} min={min} max={max} step={step}/></label>}
export function Notes({label,value,onChange,rows=4}:{label:string;value:string;onChange:(v:string)=>void;rows?:number}){return <label className="field">{label}<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function ParticipantPicker({value:p,onChange,families,disabled=false}:{value:Participants;onChange:(p:Participants)=>void;families:Family[];disabled?:boolean}){
 const base=useId(),selected=participantIds(p,families);
 function family(f:Family,checked:boolean){let next={...p,mode:'selected' as const,familyIds:p.mode==='all'?families.map(x=>x.id):[...p.familyIds],memberIds:[...p.memberIds],excludedIds:[...p.excludedIds]};const ids=f.members.map(m=>m.id);next.familyIds=checked?[...new Set([...next.familyIds,f.id])]:next.familyIds.filter(id=>id!==f.id);next.memberIds=next.memberIds.filter(id=>!ids.includes(id));next.excludedIds=next.excludedIds.filter(id=>!ids.includes(id));onChange(next)}
 function member(id:string,checked:boolean,f:Family){const implied=p.mode==='all'||p.familyIds.includes(f.id);onChange({...p,mode:p.mode==='pending'?'selected':p.mode,memberIds:implied?p.memberIds:checked?[...new Set([...p.memberIds,id])]:p.memberIds.filter(x=>x!==id),excludedIds:checked?p.excludedIds.filter(x=>x!==id):implied?[...new Set([...p.excludedIds,id])]:p.excludedIds})}
 return <div className="participant-picker"><div className="between"><b><Users size={16}/> 参与家人</b><small>{selected.length} 人</small></div><RadioGroup className="participant-modes" value={p.mode} disabled={disabled} onValueChange={v=>onChange({...p,mode:v as Participants['mode'],familyIds:[],memberIds:[],excludedIds:[]})}>{[['all','全员'],['selected','自己选'],['pending','待定']].map(([v,label])=><label key={v} htmlFor={base+v}><RadioGroupItem value={v} id={base+v}/>{label}</label>)}</RadioGroup><div className="picker-families">{families.map(f=><div className="picker-family" key={f.id}><label className="family-check"><Checkbox disabled={disabled||p.mode==='pending'||!f.members.length} checked={f.members.length&&f.members.every(m=>selected.includes(m.id))?true:f.members.some(m=>selected.includes(m.id))?'indeterminate':false} onCheckedChange={v=>family(f,v===true)}/><b>{f.name}</b><small>整家选择</small></label><div className="member-chips">{f.members.map(m=><label key={m.id} className={selected.includes(m.id)?'member-chip checked':'member-chip'}><Checkbox disabled={disabled||p.mode==='pending'} checked={selected.includes(m.id)} onCheckedChange={v=>member(m.id,v===true,f)}/>{m.name}</label>)}</div></div>)}</div><p className="muted">{p.mode==='all'?'全员会自动包含以后新增的家人，可单独取消某位成员。':p.mode==='selected'?'整家勾选会包含该家庭以后新增的成员。':'参与名单暂不确定。'}</p><Field label="参与备注（如：我可能参加）" value={p.note} onChange={note=>onChange({...p,note})}/></div>
}
export function FamilyEditor({families,onChange,disabled}:{families:Family[];onChange:(f:Family[])=>void;disabled:boolean}){return <div className="families-editor">{families.map(f=><section className="family-card" key={f.id}><div className="between"><Field label="家庭名称" required value={f.name} onChange={name=>onChange(families.map(x=>x.id===f.id?{...x,name}:x))}/>{!disabled&&<button type="button" className="btn danger" disabled={families.length<=1} onClick={()=>onChange(families.filter(x=>x.id!==f.id))}><Trash2 size={15}/>移除家庭</button>}</div><div className="member-edit-grid">{f.members.map((m,i)=><div className="member-edit" key={m.id}><Field label={`成员 ${i+1}`} required value={m.name} onChange={name=>onChange(families.map(x=>x.id===f.id?{...x,members:x.members.map(y=>y.id===m.id?{...y,name}:y)}:x))}/>{!disabled&&<button aria-label={'移除成员'+m.name} type="button" onClick={()=>onChange(families.map(x=>x.id===f.id?{...x,members:x.members.filter(y=>y.id!==m.id)}:x))}><Trash2 size={15}/></button>}</div>)}</div>{!disabled&&<button className="btn" type="button" onClick={()=>onChange(families.map(x=>x.id===f.id?{...x,members:[...x.members,{id:uid(),name:''}]}:x))}><Plus size={15}/>添加成员</button>}</section>)}{!disabled&&<button className="btn" type="button" onClick={()=>onChange([...families,{id:uid(),name:'新家庭',members:[{id:uid(),name:''}]}])}><Plus size={16}/>添加家庭</button>}</div>}
export function PlaceFields({place:p,onChange,category=true,showName=true,statusOptions,onUploadBusy,labels=defaultCategoryLabels}:{place:Place;onChange:(p:Place)=>void;category?:boolean;showName?:boolean;statusOptions:string[];onUploadBusy?:(b:boolean)=>void;labels?:Record<string,string>}){const update=(key:keyof Place,value:unknown)=>onChange({...p,[key]:value});return <>{showName&&<Field label={p.category==='住宿'?'住宿名称':p.category==='用车与联络'?'服务名称（如：露水河包车）':'地点 / 店铺名称'} required value={p.name} onChange={v=>update('name',v)}/>} {category&&<Choice label="地点分类" value={p.category} options={Object.keys(labels).filter(c=>c!=='必去 / 必吃').map(c=>({value:c,label:labels[c]}))} onChange={v=>update('category',v)}/>}{p.category==='景点'&&<section className="map-editor"><Choice label="是否有景区内部地图" value={p.mapEnabled?"yes":"no"} options={[{value:"no",label:"否 · 不显示地图图标"},{value:"yes",label:"是 · 显示地图图标"}]} onChange={v=>update('mapEnabled',v==='yes')}/>{p.mapEnabled&&<><MediaUpload onBusy={onUploadBusy} value={p.internalMap?[p.internalMap]:[]} onChange={v=>update('internalMap',v[0])}/><Notes label="地图说明 / 游览路线" value={p.mapNotes||''} onChange={v=>update('mapNotes',v)}/></>}</section>}<Choice label="价格档位" value={String(p.priceLevel||0)} options={priceLabels.map((label,i)=>({value:String(i),label}))} onChange={v=>update('priceLevel',Number(v))}/><Field label="完整地址（复制给打车软件）" value={p.address} onChange={v=>update('address',v)}/><div className="form-grid">{p.category==='用车与联络'&&<><Field label="联系人姓名 / 称呼" value={p.contactName||''} onChange={v=>update('contactName',v)}/><Field label="微信号" value={p.wechat||''} onChange={v=>update('wechat',v)}/><Field label="约定日期与时间" value={p.appointment||''} onChange={v=>update('appointment',v)}/></>}<Field label="联系电话" value={p.phone} onChange={v=>update('phone',v)}/><Field label="营业 / 接待时间" value={p.hours} onChange={v=>update('hours',v)}/></div><Notes label="地点介绍" value={p.description} onChange={v=>update('description',v)}/><Notes label="想体验 / 必吃 / 套餐亮点" value={p.highlights} onChange={v=>update('highlights',v)}/><div className="form-grid"><Field label="店铺 / 预订链接" type="url" value={p.url} onChange={v=>update('url',v)}/><Field label="地图链接" type="url" value={p.mapUrl} onChange={v=>update('mapUrl',v)}/></div><Field label="介绍来源链接" type="url" value={p.source} onChange={v=>update('source',v)}/><Choice label="状态" options={statusOptions} value={p.status} onChange={v=>update('status',v)}/><Notes label="备注 / 注意事项" value={p.notes} onChange={v=>update('notes',v)}/><label className="check-line"><Checkbox checked={p.favorite} onCheckedChange={v=>update('favorite',v===true)}/>收藏为{labels['必去 / 必吃']}</label></>}
export function PlacePicker({places,selected,onChange,onDetail,labels=defaultCategoryLabels}:{places:Place[];selected:string[];onChange:(ids:string[])=>void;onDetail:(id:string)=>void;labels?:Record<string,string>}){return <div className="place-picker"><b>关联地点 / 候选店铺</b><p className="muted">可多选候选项；名称、地址和介绍会跟随地点资料更新。</p><div className="place-options">{places.map(p=><div className="place-option" key={p.id}><label><Checkbox checked={selected.includes(p.id)} onCheckedChange={v=>onChange(v?[...selected,p.id]:selected.filter(id=>id!==p.id))}/><span>{p.name}<small>{labels[p.category]} · {p.status}</small></span></label><button type="button" onClick={()=>onDetail(p.id)} aria-label={'查看'+p.name}>详情 ↗</button></div>)}</div>{!places.length&&<p className="muted">先在“地点收藏”添加地点或店铺。</p>}</div>}
export function PlaceDetail({place:p,onClose,onEdit,editing,copy,labels=defaultCategoryLabels}:{place:Place|null;onClose:()=>void;onEdit:(p:Place)=>void;editing:boolean;copy:(s:string)=>void;labels?:Record<string,string>}){return <Sheet open={!!p} onOpenChange={v=>!v&&onClose()}><SheetContent className="place-detail">{p&&<><div className="place-detail-cover"><span className="eyebrow">{labels[p.category]} · {p.status}</span><SheetTitle>{p.favorite&&<Star size={20}/>} {p.name}</SheetTitle>{p.priceLevel? <p className="price-level" aria-label={priceLabels[p.priceLevel]}>{'$'.repeat(p.priceLevel)} · {priceLabels[p.priceLevel].split(' · ')[1]}</p>:null}<SheetDescription>{p.description||'介绍待补充。'}</SheetDescription></div><div className="place-detail-body"><div className="address-box"><MapPin size={20}/><div><b>到这里去</b><p>{p.address||'详细地址待补充，请先核对商家提供的定位。'}</p><button className="btn" disabled={!p.address} onClick={()=>copy(p.address)}><Copy size={15}/>复制地址</button></div></div>{p.category==='用车与联络'&&<section><h3>联系与约定</h3><p>联系人：{p.contactName||'待补充'}</p><p>微信：{p.wechat||'待补充'}</p><p>约定时间：{p.appointment||'待补充'}</p></section>}{p.category==='景点'&&p.mapEnabled&&<InternalMap place={p}/>}<div></div>{[['想体验 / 必吃',p.highlights],['营业 / 接待时间',p.hours],['联系电话',p.phone],['补充备注',p.notes]].map(([title,body])=><section key={title}><h3>{title}</h3><p className="prewrap">{body||'待补充'}</p></section>)}<div className="detail-links">{[['打开地图',p.mapUrl],['店铺 / 预订',p.url],['介绍来源',p.source]].map(([label,url])=>safeUrl(url)&&<a key={label} href={safeUrl(url)} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{label}</a>)}</div>{editing&&<button className="btn primary" onClick={()=>{onClose();onEdit(p)}}>编辑这份地点资料</button>}</div></>}</SheetContent></Sheet>}
export function emptyPlace(category='景点'):Place{return {id:uid(),name:'',category,address:'',description:'',highlights:'',hours:'',phone:'',url:'',mapUrl:'',source:'',notes:'',status:'候选',favorite:false}}

export function InternalMap({place:p,compact=false}:{place:Place;compact?:boolean}){const [open,setOpen]=useState(false);return <section className={compact?"map-shortcut":"internal-map"}>{!compact&&<><h3>景区内部地图</h3><p>{p.internalMap?'查看景区内各游览点与路线。':'地图准备中，后续会在这里补上。'}</p></>}<button className={compact?'icon-button':'btn'} aria-label={'查看'+p.name+'内部地图'} title="景区内部地图" onClick={()=>setOpen(true)}>{compact?<Map size={18}/>:<>查看内部地图 ↗</>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="trip-dialog map-dialog"><DialogTitle>{p.name} · 内部地图</DialogTitle><DialogDescription>{p.mapNotes||'地图与游览路线资料'}</DialogDescription>{p.internalMap?<a href={'/api/media/'+p.internalMap.id} target="_blank" rel="noreferrer"><img className="park-map-image" src={'/api/media/'+p.internalMap.id} alt={p.name+'内部地图'}/><span>打开原图放大查看 ↗</span></a>:<div className="empty map-placeholder">内部地图待补充<br/><small>在编辑地点资料时上传制作好的地图。</small></div>}</DialogContent></Dialog></section>}
